export {default as SignupPage} from "../Pages/auth/SignupPage"
export {default as SigninPage} from "../Pages/auth/SigninPage"
export {default as CheckoutPage} from "../Pages/CheckoutPage/CheckoutPage"
export {default as CategoryPage} from "../Pages/CategoryPage/CategoryPage"
export { default as CardPage} from "../Pages/ProductPage/CardPage"
export {default as DashboardPage} from "../Pages/DashboardPage/DashboardPage"
export {default as ProductDetailspage} from "../Pages/ProductPage/ProductDetailspage"
